
baseURL: https://danielalcaide.com
title: Daniel Alcaide

pagination:
  disableAliases: false
  pagerSize: 5

theme: "PaperMod"
defaultContentLanguage: es
languageCode: es

markup:
  goldmark:
    renderer:
      unsafe: true

enableRobotsTXT: true

minify:
    disableXML: true
    minifyOutput: false

languages:
  es:
    languageName: "Espa√±ol"
    weight: 1
    # home-info mode
    params:
      homeInfoParams:
        Title: "\U0001F44B Hola, soy Daniel Alcaide"
        Content: Este es mi sitio web personal donde escribo sobre ciencia de datos.

  # en:
  #   languageName: "English"
  #   weight: 2
  #   homeInfoParams:
  #     Title: "\U0001F44B Hi, I'm Daniel Alcaide"
  #     Content: This is my personal website where I write about data science. 
      
params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Daniel Alcaide
    description: "Data Scientist"
    keywords: [Blog, Portfolio, Data Science]
    author: Me
    DateFormat: "02-01-2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false

    socialIcons:
      - name: "github"
        url: "https://github.com/danielalcaide"
      - name: "linkedin"
        url: "https://www.linkedin.com/in/daniel-alcaide/"
      - name: "twitter"
        url: "https://twitter.com/danielalcaide_"
        