[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.151.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_CACHEDIR = ".hugo_cache"

[context]
[context.branch-deploy]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.production]
